spring:
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      username: root
      password: pass
      port: 27017
      database: academiaapp

jjwt:
  secret: 4u7x!A%D*G-KaNdRgUkXp2s5v8y/B?E(H+MbQeShVmYq3t6w9z$C&F)J@NcRfUjW
  expiration: 120

springreactive:
  usuario: admin
  pass: root

